export interface SubItem {
  name: string;
  href: string;
  badge?: string;
}

export interface SectionDefinition {
  id: number;
  category: 
    | "Public / Marketing" 
    | "Authentication & Onboarding" 
    | "Customer Portal" 
    | "CA Practice OS" 
    | "Super Admin Console" 
    | "Global Error & System";
  title: string;
  tagline: string;
  primaryHref: string;
  badge: string;
  iconName: string;
  items: SubItem[];
}

export const ALL_47_SECTIONS: SectionDefinition[] = [
  // 01. Public / Marketing
  {
    id: 1,
    category: "Public / Marketing",
    title: "01. Public / Marketing",
    tagline: "High-conversion public portal, services directory, tax calculator, and compliance resources.",
    primaryHref: "/",
    badge: "Public Suite",
    iconName: "Globe",
    items: [
      { name: "Landing Page", href: "/" },
      { name: "About Us", href: "/about" },
      { name: "Services", href: "/services" },
      { name: "Tax Services", href: "/tax-services" },
      { name: "CA Services", href: "/ca-services" },
      { name: "Pricing", href: "/pricing" },
      { name: "How It Works", href: "/how-it-works" },
      { name: "Features", href: "/features" },
      { name: "Find a CA", href: "/find-ca" },
      { name: "CA Directory", href: "/find-ca/directory" },
      { name: "CA Public Profile", href: "/ca/rajesh-sharma" },
      { name: "Testimonials", href: "/testimonials" },
      { name: "FAQ", href: "/faq" },
      { name: "Contact Us", href: "/contact" },
      { name: "Blog", href: "/blog" },
      { name: "Blog Details", href: "/blog/union-budget-2026-tax-slabs-guide" },
      { name: "Tax Resources", href: "/tax-resources" },
      { name: "Tax Calculator", href: "/tax-calculator" },
      { name: "Tax Deadline Calendar", href: "/tax-calendar" },
      { name: "Careers", href: "/careers" },
      { name: "Terms & Conditions", href: "/terms-of-service" },
      { name: "Privacy Policy", href: "/privacy-policy" },
      { name: "Cookie Policy", href: "/cookie-policy" },
      { name: "Refund Policy", href: "/refund-policy" },
    ],
  },

  // 02. Authentication
  {
    id: 2,
    category: "Authentication & Onboarding",
    title: "02. Authentication",
    tagline: "Role-based authentication, biometric login, OTP verification, and secure password recovery.",
    primaryHref: "/login",
    badge: "Secure Auth",
    iconName: "ShieldCheck",
    items: [
      { name: "Login", href: "/login" },
      { name: "Customer Registration", href: "/register/client" },
      { name: "CA Registration", href: "/register/ca" },
      { name: "Admin Login", href: "/admin-login" },
      { name: "Email Verification", href: "/verify-email" },
      { name: "Phone Verification", href: "/verify-phone" },
      { name: "OTP Verification", href: "/verify-otp" },
      { name: "Forgot Password", href: "/forgot-password" },
      { name: "Reset Password", href: "/reset-password" },
      { name: "Create New Password", href: "/create-password" },
      { name: "Two-Factor Authentication", href: "/2fa-setup" },
      { name: "Account Verification", href: "/account-verification" },
      { name: "Account Suspended", href: "/account-suspended" },
      { name: "Session Expired", href: "/session-expired" },
      { name: "Logout Confirmation", href: "/logout" },
    ],
  },

  // 03. Customer Onboarding
  {
    id: 3,
    category: "Authentication & Onboarding",
    title: "03. Customer Onboarding",
    tagline: "6-step guided taxpayer onboarding wizard from customer type to KYC validation.",
    primaryHref: "/onboarding/client",
    badge: "KYC Wizard",
    iconName: "UserCheck",
    items: [
      { name: "Customer Welcome", href: "/onboarding/client" },
      { name: "Select Customer Type", href: "/onboarding/client" },
      { name: "Personal Information", href: "/onboarding/client" },
      { name: "Profile Photo Upload", href: "/onboarding/client" },
      { name: "Contact Information", href: "/onboarding/client" },
      { name: "Address Information", href: "/onboarding/client" },
      { name: "PAN Information", href: "/onboarding/client" },
      { name: "Aadhaar Information", href: "/onboarding/client" },
      { name: "Bank Information", href: "/onboarding/client" },
      { name: "Employment Information", href: "/onboarding/client" },
      { name: "Business Information", href: "/onboarding/client" },
      { name: "Tax Profile", href: "/onboarding/client" },
      { name: "Income Sources", href: "/onboarding/client" },
      { name: "Previous Tax Filing Information", href: "/onboarding/client" },
      { name: "KYC Upload", href: "/onboarding/client" },
      { name: "KYC Verification", href: "/account-verification" },
      { name: "Complete Profile", href: "/onboarding/client" },
      { name: "Customer Onboarding Complete", href: "/client/dashboard" },
    ],
  },

  // 04. Customer Dashboard
  {
    id: 4,
    category: "Customer Portal",
    title: "04. Customer Dashboard",
    tagline: "Tax liability summary, pending actions, filing status, and recent activity feed.",
    primaryHref: "/client/dashboard",
    badge: "Command Center",
    iconName: "LayoutDashboard",
    items: [
      { name: "Customer Dashboard", href: "/client/dashboard" },
      { name: "Tax Overview", href: "/client/dashboard" },
      { name: "Tax Liability Summary", href: "/client/dashboard" },
      { name: "Filing Status", href: "/client/dashboard" },
      { name: "Pending Documents", href: "/client/dashboard" },
      { name: "Pending Tasks", href: "/client/tasks" },
      { name: "Upcoming Deadlines", href: "/client/compliance" },
      { name: "Recent Activity", href: "/client/dashboard" },
      { name: "Recent Messages", href: "/client/chat" },
      { name: "Recent Payments", href: "/client/payments" },
      { name: "Quick Actions", href: "/client/dashboard" },
    ],
  },

  // 05. Customer Profile
  {
    id: 5,
    category: "Customer Portal",
    title: "05. Customer Profile",
    tagline: "Personal, PAN, Aadhaar, banking, employment, dependent, and KYC information.",
    primaryHref: "/client/profile",
    badge: "Master Profile",
    iconName: "User",
    items: [
      { name: "My Profile", href: "/client/profile" },
      { name: "View Profile", href: "/client/profile" },
      { name: "Edit Profile", href: "/client/profile" },
      { name: "Profile Photo", href: "/client/profile" },
      { name: "Personal Information", href: "/client/profile" },
      { name: "Contact Information", href: "/client/profile" },
      { name: "Address", href: "/client/profile" },
      { name: "PAN Details", href: "/client/profile" },
      { name: "Aadhaar Details", href: "/client/profile" },
      { name: "Bank Details", href: "/client/profile" },
      { name: "Employment Details", href: "/client/profile" },
      { name: "Business Details", href: "/client/profile" },
      { name: "Tax Information", href: "/client/profile" },
      { name: "Income Sources", href: "/client/profile" },
      { name: "Family / Dependents", href: "/client/profile" },
      { name: "KYC Information", href: "/client/profile" },
      { name: "KYC Documents", href: "/client/profile" },
      { name: "Profile Completion", href: "/client/profile" },
    ],
  },

  // 06. Customer Tax Management
  {
    id: 6,
    category: "Customer Portal",
    title: "06. Customer Tax Management",
    tagline: "Full ITR return creation, salary/capital gains, deductions, Old vs New regime, and filing receipt.",
    primaryHref: "/client/tax-returns",
    badge: "ITR Engine",
    iconName: "FileSpreadsheet",
    items: [
      { name: "Tax Dashboard", href: "/client/tax-returns" },
      { name: "Current Tax Year", href: "/client/tax-returns" },
      { name: "Create Tax Return", href: "/client/tax-returns" },
      { name: "Tax Return Details", href: "/client/tax-returns" },
      { name: "Tax Return Overview", href: "/client/tax-returns" },
      { name: "Personal Details", href: "/client/tax-returns" },
      { name: "Income Details", href: "/client/income-tax" },
      { name: "Salary Income", href: "/client/tax-returns" },
      { name: "Business Income", href: "/client/tax-returns" },
      { name: "Freelance Income", href: "/client/tax-returns" },
      { name: "Rental Income", href: "/client/tax-returns" },
      { name: "Interest Income", href: "/client/tax-returns" },
      { name: "Dividend Income", href: "/client/tax-returns" },
      { name: "Capital Gains", href: "/client/tax-returns" },
      { name: "Other Income", href: "/client/tax-returns" },
      { name: "Foreign Income", href: "/client/tax-returns" },
      { name: "Exempt Income", href: "/client/tax-returns" },
      { name: "Expense Details", href: "/client/tax-returns" },
      { name: "Investment Details", href: "/client/tax-returns" },
      { name: "Deduction Details", href: "/client/tax-returns" },
      { name: "Tax Regime", href: "/client/tax-returns" },
      { name: "Old Tax Regime", href: "/client/tax-returns" },
      { name: "New Tax Regime", href: "/client/tax-returns" },
      { name: "Tax Calculation", href: "/client/tax-returns" },
      { name: "Tax Breakdown", href: "/client/tax-returns" },
      { name: "Tax Liability", href: "/client/tax-returns" },
      { name: "Tax Refund", href: "/client/tax-returns" },
      { name: "Tax Payable", href: "/client/tax-returns" },
      { name: "Tax Summary", href: "/client/tax-returns" },
      { name: "Tax Return Review", href: "/client/tax-returns" },
      { name: "Tax Return Approval", href: "/client/tax-returns" },
      { name: "Tax Return Submission", href: "/client/tax-returns" },
      { name: "Filing Status", href: "/client/tax-returns" },
      { name: "Filing Confirmation", href: "/client/tax-returns" },
      { name: "Filing Receipt", href: "/client/tax-returns" },
      { name: "Filed Return", href: "/client/tax-returns" },
      { name: "Tax Return History", href: "/client/income-tax" },
      { name: "Previous Year Returns", href: "/client/income-tax" },
      { name: "Download Tax Return", href: "/client/tax-returns" },
    ],
  },

  // 07. Customer Documents
  {
    id: 7,
    category: "Customer Portal",
    title: "07. Customer Documents",
    tagline: "Encrypted document vault with OCR pipeline across all 15 statutory categories.",
    primaryHref: "/client/documents",
    badge: "Document Vault",
    iconName: "FileText",
    items: [
      { name: "Documents Dashboard", href: "/client/documents" },
      { name: "All Documents", href: "/client/documents" },
      { name: "My Documents", href: "/client/documents" },
      { name: "CA Requested Documents", href: "/client/documents" },
      { name: "Pending Documents", href: "/client/documents" },
      { name: "Submitted Documents", href: "/client/documents" },
      { name: "Verified Documents", href: "/client/documents" },
      { name: "Rejected Documents", href: "/client/documents" },
      { name: "Expired Documents", href: "/client/documents" },
      { name: "Upload Document", href: "/client/documents/upload" },
      { name: "Upload From Device", href: "/client/documents/upload" },
      { name: "Upload From Camera", href: "/client/documents/upload" },
      { name: "Upload Multiple Documents", href: "/client/documents/upload" },
      { name: "Document Preview", href: "/client/documents" },
      { name: "Document Details", href: "/client/documents" },
      { name: "Edit Document Information", href: "/client/documents" },
      { name: "Rename Document", href: "/client/documents" },
      { name: "Download Document", href: "/client/documents" },
      { name: "Delete Document", href: "/client/documents" },
      { name: "Share Document", href: "/client/documents" },
      { name: "Document History", href: "/client/documents" },
      { name: "Document Versions", href: "/client/documents" },
      { name: "Document Verification", href: "/client/documents" },
      { name: "Document Search", href: "/client/documents" },
      { name: "Document Filters", href: "/client/documents" },
      { name: "Document Categories: PAN", href: "/client/documents" },
      { name: "Aadhaar", href: "/client/documents" },
      { name: "Form 16", href: "/client/documents" },
      { name: "Salary Slips", href: "/client/documents" },
      { name: "Bank Statements", href: "/client/documents" },
      { name: "Investment Proofs", href: "/client/documents" },
      { name: "Insurance Documents", href: "/client/documents" },
      { name: "Loan Documents", href: "/client/documents" },
      { name: "Property Documents", href: "/client/documents" },
      { name: "Rent Documents", href: "/client/documents" },
      { name: "Business Documents", href: "/client/documents" },
      { name: "GST Documents", href: "/client/documents" },
      { name: "ITR Documents", href: "/client/documents" },
      { name: "Tax Receipts", href: "/client/documents" },
      { name: "Other Documents", href: "/client/documents" },
    ],
  },

  // 08. Customer CA Management
  {
    id: 8,
    category: "Customer Portal",
    title: "08. Customer CA Management",
    tagline: "Find Chartered Accountants, inspect ICAI credentials, send hire proposals, and manage relationship.",
    primaryHref: "/client/my-ca",
    badge: "CA Network",
    iconName: "Briefcase",
    items: [
      { name: "My CA", href: "/client/my-ca" },
      { name: "Find CA", href: "/client/find-ca" },
      { name: "Search CA", href: "/client/find-ca/search" },
      { name: "Filter CA", href: "/client/find-ca" },
      { name: "CA Directory", href: "/client/find-ca" },
      { name: "CA Profile", href: "/client/find-ca/ca-1" },
      { name: "CA Services", href: "/client/find-ca/ca-1" },
      { name: "CA Experience", href: "/client/find-ca/ca-1" },
      { name: "CA Qualifications", href: "/client/find-ca/ca-1" },
      { name: "CA Reviews", href: "/client/find-ca/ca-1" },
      { name: "CA Availability", href: "/client/find-ca/ca-1" },
      { name: "Request CA", href: "/client/hire/ca-1" },
      { name: "Send CA Invitation", href: "/client/my-ca" },
      { name: "CA Request Status", href: "/client/my-ca" },
      { name: "CA Approval", href: "/client/my-ca" },
      { name: "CA Assignment Confirmation", href: "/client/my-ca" },
      { name: "Change CA", href: "/client/my-ca" },
      { name: "Remove CA", href: "/client/my-ca" },
      { name: "CA Relationship History", href: "/client/my-ca" },
    ],
  },

  // 09. Customer Tasks
  {
    id: 9,
    category: "Customer Portal",
    title: "09. Customer Tasks",
    tagline: "Track pending client tasks, compliance actions, comments, and attachments.",
    primaryHref: "/client/tasks",
    badge: "Action Board",
    iconName: "CheckSquare",
    items: [
      { name: "Tasks", href: "/client/tasks" },
      { name: "My Tasks", href: "/client/tasks" },
      { name: "Pending Tasks", href: "/client/tasks" },
      { name: "Completed Tasks", href: "/client/tasks" },
      { name: "Overdue Tasks", href: "/client/tasks" },
      { name: "Task Details", href: "/client/tasks" },
      { name: "Task Attachments", href: "/client/tasks" },
      { name: "Task Comments", href: "/client/tasks" },
      { name: "Task History", href: "/client/tasks" },
      { name: "Create Task", href: "/client/tasks" },
      { name: "Task Completion", href: "/client/tasks" },
    ],
  },

  // 10. Customer Messaging
  {
    id: 10,
    category: "Customer Portal",
    title: "10. Customer Messaging",
    tagline: "Real-time client ↔ CA chat, voice notes waveform, shared documents, and reactions.",
    primaryHref: "/client/chat",
    badge: "Live Chat",
    iconName: "MessageSquare",
    items: [
      { name: "Messages", href: "/client/chat" },
      { name: "Inbox", href: "/client/chat" },
      { name: "Conversations", href: "/client/chat" },
      { name: "New Conversation", href: "/client/chat" },
      { name: "Customer-CA Chat", href: "/client/chat" },
      { name: "Group Chat", href: "/client/chat" },
      { name: "Chat Details", href: "/client/chat" },
      { name: "Message Search", href: "/client/chat" },
      { name: "Shared Files", href: "/client/chat" },
      { name: "Shared Documents", href: "/client/chat" },
      { name: "Media", href: "/client/chat" },
      { name: "Voice Messages", href: "/client/chat" },
      { name: "Message Details", href: "/client/chat" },
      { name: "Message Information", href: "/client/chat" },
      { name: "Message Notifications", href: "/client/chat" },
      { name: "Chat Settings", href: "/client/chat" },
      { name: "Block User", href: "/client/chat" },
      { name: "Report User", href: "/client/chat" },
      { name: "Real-Time Chat Features: Online Status", href: "/client/chat" },
      { name: "Offline Status", href: "/client/chat" },
      { name: "Last Seen", href: "/client/chat" },
      { name: "Typing Indicator", href: "/client/chat" },
      { name: "Message Sent", href: "/client/chat" },
      { name: "Message Delivered", href: "/client/chat" },
      { name: "Message Read", href: "/client/chat" },
      { name: "Message Reply", href: "/client/chat" },
      { name: "Message Forward", href: "/client/chat" },
      { name: "Message Edit", href: "/client/chat" },
      { name: "Message Delete", href: "/client/chat" },
      { name: "Message Reaction", href: "/client/chat" },
    ],
  },

  // 11. Customer Calls
  {
    id: 11,
    category: "Customer Portal",
    title: "11. Customer Calls",
    tagline: "Encrypted HD voice/video consultations with split-screen document viewer.",
    primaryHref: "/client/calls",
    badge: "Video Room",
    iconName: "Video",
    items: [
      { name: "Calls", href: "/client/calls" },
      { name: "Voice Call", href: "/client/calls" },
      { name: "Video Call", href: "/client/calls" },
      { name: "Incoming Call", href: "/client/calls" },
      { name: "Outgoing Call", href: "/client/calls" },
      { name: "Active Call", href: "/client/calls" },
      { name: "Call Details", href: "/client/calls" },
      { name: "Call History", href: "/client/calls" },
      { name: "Missed Calls", href: "/client/calls" },
      { name: "Screen Sharing", href: "/client/calls" },
    ],
  },

  // 12. Customer Appointments
  {
    id: 12,
    category: "Customer Portal",
    title: "12. Customer Appointments",
    tagline: "Book consultation slots with verified CAs, manage reschedule/cancel, and review notes.",
    primaryHref: "/client/meetings",
    badge: "Booking",
    iconName: "Calendar",
    items: [
      { name: "Appointments", href: "/client/meetings" },
      { name: "Book Appointment", href: "/client/meetings" },
      { name: "Select CA", href: "/client/meetings" },
      { name: "CA Availability", href: "/client/meetings" },
      { name: "Select Date", href: "/client/meetings" },
      { name: "Select Time", href: "/client/meetings" },
      { name: "Appointment Confirmation", href: "/client/meetings" },
      { name: "Upcoming Appointments", href: "/client/meetings" },
      { name: "Past Appointments", href: "/client/meetings" },
      { name: "Appointment Details", href: "/client/meetings" },
      { name: "Reschedule Appointment", href: "/client/meetings" },
      { name: "Cancel Appointment", href: "/client/meetings" },
      { name: "Appointment History", href: "/client/meetings" },
      { name: "Consultation Notes", href: "/client/meetings" },
    ],
  },

  // 13. Customer Payments
  {
    id: 13,
    category: "Customer Portal",
    title: "13. Customer Payments",
    tagline: "UPI, Cards, and NetBanking checkout, transaction receipts, GST tax invoices, and refunds.",
    primaryHref: "/client/payments",
    badge: "Billing",
    iconName: "CreditCard",
    items: [
      { name: "Payments", href: "/client/payments" },
      { name: "Payment Dashboard", href: "/client/payments" },
      { name: "Payment Methods", href: "/client/payments" },
      { name: "Add Payment Method", href: "/client/payments" },
      { name: "Checkout", href: "/client/payments" },
      { name: "Payment Processing", href: "/client/payments" },
      { name: "Payment Success", href: "/client/payments" },
      { name: "Payment Failed", href: "/client/payments" },
      { name: "Payment Cancelled", href: "/client/payments" },
      { name: "Transaction History", href: "/client/payments" },
      { name: "Transaction Details", href: "/client/payments" },
      { name: "Invoices", href: "/client/invoices" },
      { name: "Invoice Details", href: "/client/invoices" },
      { name: "Download Invoice", href: "/client/invoices" },
      { name: "Refund Status", href: "/client/payments" },
      { name: "Payment Receipts", href: "/client/invoices" },
    ],
  },

  // 14. Customer Notifications
  {
    id: 14,
    category: "Customer Portal",
    title: "14. Customer Notifications",
    tagline: "Centralized feed across tax deadlines, documents, messages, payments, and system notices.",
    primaryHref: "/client/notifications",
    badge: "Alert Feed",
    iconName: "Bell",
    items: [
      { name: "Notifications", href: "/client/notifications" },
      { name: "All Notifications", href: "/client/notifications" },
      { name: "Tax Notifications", href: "/client/notifications" },
      { name: "Document Notifications", href: "/client/notifications" },
      { name: "Message Notifications", href: "/client/notifications" },
      { name: "Payment Notifications", href: "/client/notifications" },
      { name: "Appointment Notifications", href: "/client/notifications" },
      { name: "Task Notifications", href: "/client/notifications" },
      { name: "Deadline Notifications", href: "/client/notifications" },
      { name: "System Notifications", href: "/client/notifications" },
      { name: "Notification Details", href: "/client/notifications" },
      { name: "Notification Settings", href: "/client/notifications" },
    ],
  },

  // 15. Customer Tax Calendar
  {
    id: 15,
    category: "Customer Portal",
    title: "15. Customer Tax Calendar",
    tagline: "Statutory filing deadlines (GSTR-1, 3B, ITR, TDS), custom reminders, and alerts.",
    primaryHref: "/client/calendar",
    badge: "Deadlines",
    iconName: "Clock",
    items: [
      { name: "Tax Calendar", href: "/client/calendar" },
      { name: "Upcoming Deadlines", href: "/client/compliance" },
      { name: "Filing Deadlines", href: "/client/calendar" },
      { name: "Payment Deadlines", href: "/client/calendar" },
      { name: "Tax Events", href: "/client/calendar" },
      { name: "Deadline Details", href: "/client/calendar" },
      { name: "Add Reminder", href: "/client/calendar" },
      { name: "My Reminders", href: "/client/calendar" },
      { name: "Reminder Settings", href: "/client/calendar" },
    ],
  },

  // 16. Customer Reports
  {
    id: 16,
    category: "Customer Portal",
    title: "16. Customer Reports",
    tagline: "Gross income breakdown, deductions, tax liability history, and annual tax summary.",
    primaryHref: "/client/tax-reports",
    badge: "Analytics",
    iconName: "BarChart3",
    items: [
      { name: "Reports", href: "/client/tax-reports" },
      { name: "Tax Report", href: "/client/tax-reports" },
      { name: "Income Report", href: "/client/tax-reports" },
      { name: "Expense Report", href: "/client/tax-reports" },
      { name: "Deduction Report", href: "/client/tax-reports" },
      { name: "Tax Liability Report", href: "/client/tax-reports" },
      { name: "Filing Report", href: "/client/tax-reports" },
      { name: "Payment Report", href: "/client/tax-reports" },
      { name: "Document Report", href: "/client/tax-reports" },
      { name: "Annual Tax Summary", href: "/client/tax-reports" },
      { name: "Download Report", href: "/client/tax-reports" },
    ],
  },

  // 17. Customer Settings
  {
    id: 17,
    category: "Customer Portal",
    title: "17. Customer Settings",
    tagline: "Security credentials, 2FA hardware tokens, connected devices, privacy, and data export.",
    primaryHref: "/client/settings",
    badge: "Preferences",
    iconName: "Settings",
    items: [
      { name: "Settings", href: "/client/settings" },
      { name: "Account Settings", href: "/client/settings" },
      { name: "Profile Settings", href: "/client/profile" },
      { name: "Security Settings", href: "/client/settings" },
      { name: "Password Settings", href: "/client/settings" },
      { name: "Two-Factor Authentication", href: "/2fa-setup" },
      { name: "Login Sessions", href: "/client/settings" },
      { name: "Connected Devices", href: "/client/settings" },
      { name: "Privacy Settings", href: "/client/settings" },
      { name: "Notification Settings", href: "/client/settings" },
      { name: "Chat Settings", href: "/client/settings" },
      { name: "Payment Settings", href: "/client/settings" },
      { name: "Language Settings", href: "/client/settings" },
      { name: "Theme Settings", href: "/client/settings" },
      { name: "Data & Storage", href: "/client/settings" },
      { name: "Download My Data", href: "/client/settings" },
      { name: "Delete Account", href: "/client/settings" },
      { name: "Logout", href: "/logout" },
    ],
  },

  // 18. CA Onboarding
  {
    id: 18,
    category: "CA Practice OS",
    title: "18. CA Onboarding",
    tagline: "Practice registration, ICAI licensure upload, verification, fee structure, and calendar setup.",
    primaryHref: "/ca/onboarding",
    badge: "CA Setup",
    iconName: "Award",
    items: [
      { name: "CA Welcome", href: "/ca/onboarding" },
      { name: "CA Personal Information", href: "/ca/onboarding" },
      { name: "Profile Photo Upload", href: "/ca/onboarding" },
      { name: "Contact Information", href: "/ca/onboarding" },
      { name: "Address", href: "/ca/onboarding" },
      { name: "Professional Information", href: "/ca/onboarding" },
      { name: "Qualification", href: "/ca/onboarding" },
      { name: "Experience", href: "/ca/onboarding" },
      { name: "Specialization", href: "/ca/onboarding" },
      { name: "CA Registration Details", href: "/ca/onboarding" },
      { name: "License / Certificate Upload", href: "/ca/onboarding" },
      { name: "KYC Documents", href: "/ca/onboarding" },
      { name: "Bank Details", href: "/ca/onboarding" },
      { name: "Service Information", href: "/ca/onboarding" },
      { name: "Service Pricing", href: "/ca/onboarding" },
      { name: "Availability", href: "/ca/onboarding" },
      { name: "CA Verification", href: "/ca/onboarding" },
      { name: "Verification Status", href: "/ca/onboarding" },
      { name: "CA Onboarding Complete", href: "/ca/dashboard" },
    ],
  },

  // 19. CA Dashboard
  {
    id: 19,
    category: "CA Practice OS",
    title: "19. CA Dashboard",
    tagline: "Practice revenue, active client cases, pending documents, filing deadlines, and quick actions.",
    primaryHref: "/ca/dashboard",
    badge: "Practice HQ",
    iconName: "LayoutDashboard",
    items: [
      { name: "CA Dashboard", href: "/ca/dashboard" },
      { name: "Business Overview", href: "/ca/dashboard" },
      { name: "Client Overview", href: "/ca/clients" },
      { name: "Active Cases", href: "/ca/cases" },
      { name: "Pending Documents", href: "/ca/documents" },
      { name: "Pending Tasks", href: "/ca/tasks" },
      { name: "Upcoming Deadlines", href: "/ca/calendar" },
      { name: "Upcoming Appointments", href: "/ca/appointments" },
      { name: "Filing Overview", href: "/ca/income-tax" },
      { name: "Revenue Overview", href: "/ca/payments" },
      { name: "Recent Activity", href: "/ca/dashboard" },
      { name: "Quick Actions", href: "/ca/dashboard" },
    ],
  },

  // 20. CA Profile
  {
    id: 20,
    category: "CA Practice OS",
    title: "20. CA Profile",
    tagline: "Public practitioner dossier, certifications, verified badge, pricing, and client feedback.",
    primaryHref: "/ca/profile",
    badge: "ICAI Verified",
    iconName: "Award",
    items: [
      { name: "My CA Profile", href: "/ca/profile" },
      { name: "View Profile", href: "/ca/profile" },
      { name: "Edit Profile", href: "/ca/edit-profile" },
      { name: "Profile Photo", href: "/ca/edit-profile" },
      { name: "Personal Information", href: "/ca/edit-profile" },
      { name: "Professional Information", href: "/ca/profile" },
      { name: "Qualifications", href: "/ca/profile" },
      { name: "Certifications", href: "/ca/profile" },
      { name: "Experience", href: "/ca/profile" },
      { name: "Specializations", href: "/ca/profile" },
      { name: "Services", href: "/ca/services" },
      { name: "Pricing", href: "/ca/services" },
      { name: "Availability", href: "/ca/availability" },
      { name: "Verification", href: "/ca/profile" },
      { name: "Reviews", href: "/ca/reviews" },
      { name: "Client Feedback", href: "/ca/reviews" },
      { name: "Profile Preview", href: "/ca/profile" },
    ],
  },

  // 21. CA Client Management
  {
    id: 21,
    category: "CA Practice OS",
    title: "21. CA Client Management",
    tagline: "Client CRM, invitations, tax profiles, activity timeline, and dossier management.",
    primaryHref: "/ca/clients",
    badge: "Client CRM",
    iconName: "Users",
    items: [
      { name: "Clients", href: "/ca/clients" },
      { name: "All Clients", href: "/ca/clients" },
      { name: "Active Clients", href: "/ca/clients" },
      { name: "Pending Clients", href: "/ca/clients" },
      { name: "Archived Clients", href: "/ca/clients" },
      { name: "Add Client", href: "/ca/clients/add" },
      { name: "Invite Client", href: "/ca/clients/add" },
      { name: "Client Request", href: "/ca/clients" },
      { name: "Client Details", href: "/ca/clients/cl-1" },
      { name: "Client Profile", href: "/ca/clients/cl-1" },
      { name: "Client Tax Profile", href: "/ca/clients/cl-1" },
      { name: "Client Documents", href: "/ca/documents" },
      { name: "Client Tax Returns", href: "/ca/income-tax" },
      { name: "Client Tasks", href: "/ca/tasks" },
      { name: "Client Messages", href: "/ca/chat" },
      { name: "Client Appointments", href: "/ca/appointments" },
      { name: "Client Payments", href: "/ca/payments" },
      { name: "Client Notes", href: "/ca/clients/cl-1" },
      { name: "Client Activity", href: "/ca/clients/cl-1" },
      { name: "Client Timeline", href: "/ca/clients/cl-1" },
      { name: "Client History", href: "/ca/clients/cl-1" },
      { name: "Remove Client", href: "/ca/clients" },
      { name: "Archive Client", href: "/ca/clients" },
    ],
  },

  // 22. CA Tax Cases
  {
    id: 22,
    category: "CA Practice OS",
    title: "22. CA Tax Cases",
    tagline: "Track and organize client cases across draft, review, approval, and filed stages.",
    primaryHref: "/ca/cases",
    badge: "Cases Pipeline",
    iconName: "Briefcase",
    items: [
      { name: "Tax Cases", href: "/ca/cases" },
      { name: "All Cases", href: "/ca/cases" },
      { name: "New Case", href: "/ca/cases" },
      { name: "Active Cases", href: "/ca/cases" },
      { name: "Pending Cases", href: "/ca/cases" },
      { name: "Review Cases", href: "/ca/cases" },
      { name: "Approval Cases", href: "/ca/cases" },
      { name: "Filed Cases", href: "/ca/cases" },
      { name: "Completed Cases", href: "/ca/cases" },
      { name: "Case Details", href: "/ca/cases" },
      { name: "Case Overview", href: "/ca/cases" },
      { name: "Case Documents", href: "/ca/documents" },
      { name: "Case Tasks", href: "/ca/tasks" },
      { name: "Case Messages", href: "/ca/chat" },
      { name: "Case Timeline", href: "/ca/cases" },
      { name: "Case Notes", href: "/ca/cases" },
      { name: "Case Activity", href: "/ca/cases" },
    ],
  },

  // 23. CA Document Management
  {
    id: 23,
    category: "CA Practice OS",
    title: "23. CA Document Management",
    tagline: "Manage client uploads, issue missing document requisitions, verify proofs, and review versions.",
    primaryHref: "/ca/documents",
    badge: "Audit Vault",
    iconName: "FolderLock",
    items: [
      { name: "Documents", href: "/ca/documents" },
      { name: "All Documents", href: "/ca/documents" },
      { name: "Client Documents", href: "/ca/documents" },
      { name: "Requested Documents", href: "/ca/document-requests" },
      { name: "Pending Documents", href: "/ca/documents" },
      { name: "Received Documents", href: "/ca/documents" },
      { name: "Verified Documents", href: "/ca/documents" },
      { name: "Rejected Documents", href: "/ca/documents" },
      { name: "Upload Document", href: "/ca/documents" },
      { name: "Request Document", href: "/ca/document-requests" },
      { name: "Document Details", href: "/ca/documents" },
      { name: "Document Preview", href: "/ca/documents" },
      { name: "Document Verification", href: "/ca/documents" },
      { name: "Document Comments", href: "/ca/documents" },
      { name: "Document History", href: "/ca/documents" },
      { name: "Document Versions", href: "/ca/documents" },
      { name: "Download Document", href: "/ca/documents" },
      { name: "Share Document", href: "/ca/documents" },
      { name: "Delete Document", href: "/ca/documents" },
      { name: "Document Search", href: "/ca/documents" },
      { name: "Document Filters", href: "/ca/documents" },
    ],
  },

  // 24. CA Tax Workflow
  {
    id: 24,
    category: "CA Practice OS",
    title: "24. CA Tax Workflow",
    tagline: "End-to-end ITR & GST preparation pipeline from document checklist to e-filing acknowledgement.",
    primaryHref: "/ca/income-tax",
    badge: "Filing Engine",
    iconName: "Activity",
    items: [
      { name: "Start Tax Return", href: "/ca/income-tax" },
      { name: "Client Information", href: "/ca/income-tax" },
      { name: "Document Checklist", href: "/ca/income-tax" },
      { name: "Request Missing Documents", href: "/ca/document-requests" },
      { name: "Review Documents", href: "/ca/documents" },
      { name: "Extract Tax Information", href: "/ca/income-tax" },
      { name: "Verify Extracted Data", href: "/ca/income-tax" },
      { name: "Income Review", href: "/ca/income-tax" },
      { name: "Deduction Review", href: "/ca/income-tax" },
      { name: "Investment Review", href: "/ca/income-tax" },
      { name: "Tax Calculation", href: "/ca/income-tax" },
      { name: "Tax Comparison", href: "/ca/income-tax" },
      { name: "Tax Regime Comparison", href: "/ca/income-tax" },
      { name: "Tax Review", href: "/ca/income-tax" },
      { name: "Create Return Draft", href: "/ca/income-tax" },
      { name: "Internal Review", href: "/ca/income-tax" },
      { name: "Send to Customer", href: "/ca/income-tax" },
      { name: "Customer Approval", href: "/ca/income-tax" },
      { name: "Submit Return", href: "/ca/income-tax" },
      { name: "Filing Status", href: "/ca/income-tax" },
      { name: "Filing Confirmation", href: "/ca/income-tax" },
      { name: "Filing Receipt", href: "/ca/income-tax" },
      { name: "Completed Return", href: "/ca/income-tax" },
    ],
  },

  // 25. CA Tasks
  {
    id: 25,
    category: "CA Practice OS",
    title: "25. CA Tasks",
    tagline: "6-stage practice workflow board: Pending → In Progress → Review → Customer Approval → Filed → Completed.",
    primaryHref: "/ca/tasks/kanban",
    badge: "6-Stage Kanban",
    iconName: "CheckSquare",
    items: [
      { name: "Task Dashboard", href: "/ca/tasks" },
      { name: "All Tasks", href: "/ca/tasks" },
      { name: "My Tasks", href: "/ca/tasks" },
      { name: "Client Tasks", href: "/ca/tasks" },
      { name: "Create Task", href: "/ca/tasks" },
      { name: "Assign Task", href: "/ca/tasks" },
      { name: "Task Details", href: "/ca/tasks/kanban" },
      { name: "Task Comments", href: "/ca/tasks/kanban" },
      { name: "Task Attachments", href: "/ca/tasks/kanban" },
      { name: "Task Timeline", href: "/ca/tasks/kanban" },
      { name: "Pending Tasks", href: "/ca/tasks" },
      { name: "Completed Tasks", href: "/ca/tasks" },
      { name: "Overdue Tasks", href: "/ca/tasks" },
    ],
  },

  // 26. CA Messaging
  {
    id: 26,
    category: "CA Practice OS",
    title: "26. CA Messaging",
    tagline: "Client conversations, internal audit channels, document review threads, and messaging security.",
    primaryHref: "/ca/chat",
    badge: "Team & Client Chat",
    iconName: "MessageSquare",
    items: [
      { name: "Messages", href: "/ca/chat" },
      { name: "Inbox", href: "/ca/chat" },
      { name: "Conversations", href: "/ca/chat" },
      { name: "New Conversation", href: "/ca/chat" },
      { name: "Client Chat", href: "/ca/chat" },
      { name: "Team Chat", href: "/ca/chat" },
      { name: "Group Chat", href: "/ca/chat" },
      { name: "Chat Details", href: "/ca/chat" },
      { name: "Shared Files", href: "/ca/chat" },
      { name: "Shared Documents", href: "/ca/chat" },
      { name: "Message Search", href: "/ca/chat" },
      { name: "Message Details", href: "/ca/chat" },
      { name: "Chat Settings", href: "/ca/chat" },
      { name: "Block User", href: "/ca/chat" },
      { name: "Report User", href: "/ca/chat" },
    ],
  },

  // 27. CA Appointments
  {
    id: 27,
    category: "CA Practice OS",
    title: "27. CA Appointments",
    tagline: "Manage consultation bookings, configure weekly availability, block slots, and record consultation notes.",
    primaryHref: "/ca/appointments",
    badge: "Schedule",
    iconName: "Calendar",
    items: [
      { name: "Appointments", href: "/ca/appointments" },
      { name: "Calendar", href: "/ca/calendar" },
      { name: "Bookings", href: "/ca/appointments" },
      { name: "Upcoming Appointments", href: "/ca/appointments" },
      { name: "Past Appointments", href: "/ca/appointments" },
      { name: "Appointment Details", href: "/ca/appointments" },
      { name: "Accept Appointment", href: "/ca/appointments" },
      { name: "Reject Appointment", href: "/ca/appointments" },
      { name: "Reschedule Appointment", href: "/ca/appointments" },
      { name: "Cancel Appointment", href: "/ca/appointments" },
      { name: "Consultation Notes", href: "/ca/appointments" },
      { name: "Availability", href: "/ca/availability" },
      { name: "Working Hours", href: "/ca/availability" },
      { name: "Block Time", href: "/ca/availability" },
    ],
  },

  // 28. CA Payments & Billing
  {
    id: 28,
    category: "CA Practice OS",
    title: "28. CA Payments & Billing",
    tagline: "Create GST-compliant invoices, track retainers, client remittances, firm wallet, and double-entry ledger.",
    primaryHref: "/ca/payments",
    badge: "Practice Billing",
    iconName: "Receipt",
    items: [
      { name: "Payments", href: "/ca/payments" },
      { name: "Payment Dashboard", href: "/ca/payments" },
      { name: "Transactions", href: "/ca/payments" },
      { name: "Transaction Details", href: "/ca/payments" },
      { name: "Client Payments", href: "/ca/payments" },
      { name: "Pending Payments", href: "/ca/payments" },
      { name: "Completed Payments", href: "/ca/payments" },
      { name: "Failed Payments", href: "/ca/payments" },
      { name: "Refunds", href: "/ca/payments" },
      { name: "Invoices", href: "/ca/invoices" },
      { name: "Create Invoice", href: "/ca/invoices/create" },
      { name: "Invoice Details", href: "/ca/invoices" },
      { name: "Edit Invoice", href: "/ca/invoices/create" },
      { name: "Send Invoice", href: "/ca/invoices" },
      { name: "Download Invoice", href: "/ca/invoices" },
      { name: "Pricing", href: "/ca/services" },
      { name: "Services Pricing", href: "/ca/services" },
      { name: "Subscription", href: "/ca/wallet" },
      { name: "Earnings", href: "/ca/payments" },
      { name: "Revenue Reports", href: "/ca/analytics" },
    ],
  },

  // 29. CA Reports & Analytics
  {
    id: 29,
    category: "CA Practice OS",
    title: "29. CA Reports & Analytics",
    tagline: "Practice velocity KPIs, client growth, unbilled retainers, filing turnaround, and audit reports.",
    primaryHref: "/ca/analytics",
    badge: "Practice BI",
    iconName: "BarChart3",
    items: [
      { name: "Analytics Dashboard", href: "/ca/analytics" },
      { name: "Client Analytics", href: "/ca/analytics" },
      { name: "Filing Analytics", href: "/ca/analytics" },
      { name: "Tax Analytics", href: "/ca/analytics" },
      { name: "Revenue Analytics", href: "/ca/analytics" },
      { name: "Payment Analytics", href: "/ca/analytics" },
      { name: "Task Analytics", href: "/ca/analytics" },
      { name: "Document Analytics", href: "/ca/analytics" },
      { name: "Appointment Analytics", href: "/ca/analytics" },
      { name: "Client Growth", href: "/ca/analytics" },
      { name: "Filing Performance", href: "/ca/analytics" },
      { name: "Revenue Report", href: "/ca/analytics" },
      { name: "Tax Report", href: "/ca/analytics" },
      { name: "Download Reports", href: "/ca/analytics" },
    ],
  },

  // 30. CA Notifications
  {
    id: 30,
    category: "CA Practice OS",
    title: "30. CA Notifications",
    tagline: "Real-time practice feed for client document submissions, filing approvals, and CBDT deadline updates.",
    primaryHref: "/ca/notifications",
    badge: "Practice Alerts",
    iconName: "Bell",
    items: [
      { name: "Notifications", href: "/ca/notifications" },
      { name: "Client Notifications", href: "/ca/notifications" },
      { name: "Tax Notifications", href: "/ca/notifications" },
      { name: "Document Notifications", href: "/ca/notifications" },
      { name: "Message Notifications", href: "/ca/notifications" },
      { name: "Payment Notifications", href: "/ca/notifications" },
      { name: "Appointment Notifications", href: "/ca/notifications" },
      { name: "Task Notifications", href: "/ca/notifications" },
      { name: "Deadline Notifications", href: "/ca/notifications" },
      { name: "System Notifications", href: "/ca/notifications" },
      { name: "Notification Settings", href: "/ca/settings/notifications" },
    ],
  },

  // 31. CA Settings
  {
    id: 31,
    category: "CA Practice OS",
    title: "31. CA Settings",
    tagline: "Firm profile, verified credentials, pricing, bank accounts for direct payouts, and security.",
    primaryHref: "/ca/settings",
    badge: "Firm Config",
    iconName: "Settings",
    items: [
      { name: "Settings", href: "/ca/settings" },
      { name: "Account Settings", href: "/ca/settings" },
      { name: "Profile Settings", href: "/ca/settings/profile" },
      { name: "Professional Settings", href: "/ca/settings/verification" },
      { name: "Service Settings", href: "/ca/services" },
      { name: "Pricing Settings", href: "/ca/services" },
      { name: "Availability Settings", href: "/ca/availability" },
      { name: "Payment Settings", href: "/ca/settings/billing" },
      { name: "Security Settings", href: "/ca/settings/security" },
      { name: "Password", href: "/ca/settings/security" },
      { name: "Two-Factor Authentication", href: "/ca/settings/security" },
      { name: "Login Sessions", href: "/ca/settings/security" },
      { name: "Connected Devices", href: "/ca/settings/security" },
      { name: "Privacy", href: "/ca/settings" },
      { name: "Notification Settings", href: "/ca/settings/notifications" },
      { name: "Chat Settings", href: "/ca/settings" },
      { name: "Data & Storage", href: "/ca/settings" },
      { name: "Download Data", href: "/ca/settings" },
      { name: "Delete Account", href: "/ca/settings" },
      { name: "Logout", href: "/logout" },
    ],
  },

  // 32. Admin Authentication
  {
    id: 32,
    category: "Super Admin Console",
    title: "32. Admin Authentication",
    tagline: "Root-level login, TOTP hardware token authentication, and cryptographic password rotation.",
    primaryHref: "/admin/login",
    badge: "Root Auth",
    iconName: "ShieldAlert",
    items: [
      { name: "Admin Login", href: "/admin/login" },
      { name: "Admin 2FA", href: "/admin/2fa" },
      { name: "Admin Forgot Password", href: "/admin/forgot-password" },
      { name: "Admin Reset Password", href: "/admin/reset-password" },
    ],
  },

  // 33. Admin Dashboard
  {
    id: 33,
    category: "Super Admin Console",
    title: "33. Admin Dashboard",
    tagline: "Platform-wide telemetry, user growth curves, filings throughput, and escrow balance.",
    primaryHref: "/admin/dashboard",
    badge: "Super Console",
    iconName: "Activity",
    items: [
      { name: "Admin Dashboard", href: "/admin/dashboard" },
      { name: "Platform Overview", href: "/admin/dashboard" },
      { name: "User Statistics", href: "/admin/users" },
      { name: "Customer Statistics", href: "/admin/customers" },
      { name: "CA Statistics", href: "/admin/ca-approvals" },
      { name: "Tax Filing Statistics", href: "/admin/tax-management" },
      { name: "Revenue Statistics", href: "/admin/revenue" },
      { name: "Payment Statistics", href: "/admin/payments" },
      { name: "Document Statistics", href: "/admin/documents" },
      { name: "Appointment Statistics", href: "/admin/appointments" },
      { name: "System Activity", href: "/admin/dashboard" },
    ],
  },

  // 34. Admin User Management
  {
    id: 34,
    category: "Super Admin Console",
    title: "34. Admin User Management",
    tagline: "Govern all customers, verified CAs, and internal team members with audit histories.",
    primaryHref: "/admin/users",
    badge: "User Directory",
    iconName: "Users",
    items: [
      { name: "Users", href: "/admin/users" },
      { name: "All Users", href: "/admin/users" },
      { name: "Customers", href: "/admin/customers" },
      { name: "CA / Accountants", href: "/admin/ca-approvals" },
      { name: "Admin Users", href: "/admin/users" },
      { name: "User Details", href: "/admin/users" },
      { name: "User Profile", href: "/admin/users" },
      { name: "Edit User", href: "/admin/users" },
      { name: "Create User", href: "/admin/users" },
      { name: "Suspend User", href: "/admin/users" },
      { name: "Activate User", href: "/admin/users" },
      { name: "Delete User", href: "/admin/users" },
      { name: "User Activity", href: "/admin/audit-logs" },
      { name: "User Login History", href: "/admin/audit-logs" },
    ],
  },

  // 35. Admin CA Verification
  {
    id: 35,
    category: "Super Admin Console",
    title: "35. Admin CA Verification",
    tagline: "Verify ICAI membership numbers, Certificates of Practice, and approve/reject practitioner listings.",
    primaryHref: "/admin/ca-approvals",
    badge: "ICAI Vetting",
    iconName: "ShieldCheck",
    items: [
      { name: "CA Verification", href: "/admin/ca-approvals" },
      { name: "Pending Verification", href: "/admin/ca-approvals" },
      { name: "CA Verification Details", href: "/admin/ca-approvals" },
      { name: "KYC Documents", href: "/admin/kyc" },
      { name: "License Documents", href: "/admin/ca-approvals" },
      { name: "Qualification Documents", href: "/admin/ca-approvals" },
      { name: "Approve CA", href: "/admin/ca-approvals" },
      { name: "Reject CA", href: "/admin/ca-approvals" },
      { name: "Request More Information", href: "/admin/ca-approvals" },
      { name: "Verification History", href: "/admin/ca-approvals" },
      { name: "Verified CA List", href: "/admin/ca-approvals" },
      { name: "Suspended CA List", href: "/admin/ca-approvals" },
    ],
  },

  // 36. Admin Customer Management
  {
    id: 36,
    category: "Super Admin Console",
    title: "36. Admin Customer Management",
    tagline: "Dedicated taxpayer profiles, document audits, filing statuses, and support records.",
    primaryHref: "/admin/customers",
    badge: "Taxpayers",
    iconName: "Users",
    items: [
      { name: "Customer Management", href: "/admin/customers" },
      { name: "Customer Details", href: "/admin/customers" },
      { name: "Customer Profile", href: "/admin/customers" },
      { name: "Customer Documents", href: "/admin/documents" },
      { name: "Customer Tax Returns", href: "/admin/tax-management" },
      { name: "Customer Activity", href: "/admin/audit-logs" },
      { name: "Customer Payments", href: "/admin/payments" },
      { name: "Customer Appointments", href: "/admin/appointments" },
      { name: "Customer Support Tickets", href: "/admin/support-tickets" },
    ],
  },

  // 37. Admin Tax Management
  {
    id: 37,
    category: "Super Admin Console",
    title: "37. Admin Tax Management",
    tagline: "CBDT tax rules, Assessment Year configuration, rebate limits, and statutory deadline schedules.",
    primaryHref: "/admin/tax-management",
    badge: "Tax Rules Engine",
    iconName: "FileSpreadsheet",
    items: [
      { name: "Tax Management", href: "/admin/tax-management" },
      { name: "Tax Returns", href: "/admin/tax-management" },
      { name: "Return Details", href: "/admin/tax-management" },
      { name: "Filing Status", href: "/admin/tax-management" },
      { name: "Filing Records", href: "/admin/tax-management" },
      { name: "Tax Configuration", href: "/admin/tax-management" },
      { name: "Tax Rules", href: "/admin/tax-management" },
      { name: "Tax Categories", href: "/admin/tax-management" },
      { name: "Tax Years", href: "/admin/tax-management" },
      { name: "Tax Deadlines", href: "/admin/tax-management" },
      { name: "Tax Services", href: "/admin/tax-management" },
      { name: "Tax Service Pricing", href: "/admin/plans" },
    ],
  },

  // 38. Admin Document Management
  {
    id: 38,
    category: "Super Admin Console",
    title: "38. Admin Document Management",
    tagline: "Enterprise document repository, OCR audit logs, storage retention policies, and category controls.",
    primaryHref: "/admin/documents",
    badge: "Storage Admin",
    iconName: "FolderLock",
    items: [
      { name: "Documents", href: "/admin/documents" },
      { name: "All Documents", href: "/admin/documents" },
      { name: "Document Details", href: "/admin/documents" },
      { name: "Document Verification", href: "/admin/documents" },
      { name: "Document Categories", href: "/admin/documents" },
      { name: "Storage Management", href: "/admin/documents" },
      { name: "Document Activity", href: "/admin/documents" },
      { name: "Document Audit History", href: "/admin/audit-logs" },
    ],
  },

  // 39. Admin Appointment Management
  {
    id: 39,
    category: "Super Admin Console",
    title: "39. Admin Appointment Management",
    tagline: "System-wide consultation bookings across all verified CAs, resolution rates, and dispute logs.",
    primaryHref: "/admin/appointments",
    badge: "Consultations",
    iconName: "Calendar",
    items: [
      { name: "Appointments", href: "/admin/appointments" },
      { name: "All Appointments", href: "/admin/appointments" },
      { name: "Upcoming Appointments", href: "/admin/appointments" },
      { name: "Completed Appointments", href: "/admin/appointments" },
      { name: "Cancelled Appointments", href: "/admin/appointments" },
      { name: "Appointment Details", href: "/admin/appointments" },
      { name: "Appointment Reports", href: "/admin/appointments" },
    ],
  },

  // 40. Admin Payment Management
  {
    id: 40,
    category: "Super Admin Console",
    title: "40. Admin Payment Management",
    tagline: "Razorpay/UPI transaction ledger, escrow payouts, refund authorizations, and plan subscriptions.",
    primaryHref: "/admin/payments",
    badge: "Escrow Ledger",
    iconName: "CreditCard",
    items: [
      { name: "Payments", href: "/admin/payments" },
      { name: "Transactions", href: "/admin/transactions" },
      { name: "Transaction Details", href: "/admin/transactions" },
      { name: "Revenue", href: "/admin/revenue" },
      { name: "Refunds", href: "/admin/payments" },
      { name: "Failed Payments", href: "/admin/payments" },
      { name: "Payment Methods", href: "/admin/payments" },
      { name: "Invoices", href: "/admin/payments" },
      { name: "Subscription Management", href: "/admin/subscriptions" },
      { name: "Pricing Management", href: "/admin/plans" },
      { name: "Payment Reports", href: "/admin/reports" },
    ],
  },

  // 41. Admin Communication
  {
    id: 41,
    category: "Super Admin Console",
    title: "41. Admin Communication",
    tagline: "Platform announcements, reported chats, moderation queues, and notification broadcast templates.",
    primaryHref: "/admin/communication",
    badge: "Broadcast",
    iconName: "Megaphone",
    items: [
      { name: "Messages", href: "/admin/communication" },
      { name: "Conversations", href: "/admin/communication" },
      { name: "Reported Messages", href: "/admin/communication" },
      { name: "Reported Users", href: "/admin/communication" },
      { name: "Communication Reports", href: "/admin/communication" },
      { name: "Notification Management", href: "/admin/announcements" },
      { name: "Send Notification", href: "/admin/announcements" },
      { name: "Notification Templates", href: "/admin/announcements" },
    ],
  },

  // 42. Admin Support
  {
    id: 42,
    category: "Super Admin Console",
    title: "42. Admin Support",
    tagline: "Multi-tier support ticketing queue, SLA tracking, resolution notes, and customer complaints.",
    primaryHref: "/admin/support-tickets",
    badge: "Support Desk",
    iconName: "LifeBuoy",
    items: [
      { name: "Support Dashboard", href: "/admin/support-tickets" },
      { name: "Support Tickets", href: "/admin/support-tickets" },
      { name: "Open Tickets", href: "/admin/support-tickets" },
      { name: "Pending Tickets", href: "/admin/support-tickets" },
      { name: "Resolved Tickets", href: "/admin/support-tickets" },
      { name: "Ticket Details", href: "/admin/support-tickets" },
      { name: "Assign Ticket", href: "/admin/support-tickets" },
      { name: "Ticket Conversation", href: "/admin/support-tickets" },
      { name: "FAQ Management", href: "/admin/content/faqs" },
      { name: "Help Center Management", href: "/admin/content" },
      { name: "Feedback Management", href: "/admin/support-tickets" },
      { name: "Complaints", href: "/admin/support-tickets" },
    ],
  },

  // 43. Admin Content Management
  {
    id: 43,
    category: "Super Admin Console",
    title: "43. Admin Content Management",
    tagline: "Publish tax guides, manage blog articles, author FAQs, and curate verified testimonials.",
    primaryHref: "/admin/content",
    badge: "CMS",
    iconName: "FileText",
    items: [
      { name: "Blog Management", href: "/admin/content/blogs" },
      { name: "Create Blog", href: "/admin/content/blogs" },
      { name: "Edit Blog", href: "/admin/content/blogs" },
      { name: "Blog Categories", href: "/admin/content/blogs" },
      { name: "Tax Resources", href: "/admin/content" },
      { name: "Resource Management", href: "/admin/content" },
      { name: "FAQ Management", href: "/admin/content/faqs" },
      { name: "Homepage Content", href: "/admin/content" },
      { name: "Service Management", href: "/admin/content" },
      { name: "Testimonial Management", href: "/admin/content" },
    ],
  },

  // 44. Admin Analytics
  {
    id: 44,
    category: "Super Admin Console",
    title: "44. Admin Analytics",
    tagline: "Platform growth metrics, practitioner conversion, filing turnaround times, and revenue cohorts.",
    primaryHref: "/admin/analytics",
    badge: "BI Suite",
    iconName: "BarChart3",
    items: [
      { name: "Analytics Dashboard", href: "/admin/analytics" },
      { name: "User Analytics", href: "/admin/analytics" },
      { name: "Customer Analytics", href: "/admin/analytics" },
      { name: "CA Analytics", href: "/admin/analytics" },
      { name: "Tax Analytics", href: "/admin/analytics" },
      { name: "Filing Analytics", href: "/admin/analytics" },
      { name: "Revenue Analytics", href: "/admin/revenue" },
      { name: "Payment Analytics", href: "/admin/revenue" },
      { name: "Document Analytics", href: "/admin/analytics" },
      { name: "Appointment Analytics", href: "/admin/analytics" },
      { name: "Support Analytics", href: "/admin/support-tickets" },
      { name: "Platform Growth", href: "/admin/analytics" },
      { name: "Export Reports", href: "/admin/reports" },
    ],
  },

  // 45. Admin Security
  {
    id: 45,
    category: "Super Admin Console",
    title: "45. Admin Security",
    tagline: "Immutable audit logs, API key issuance, role permissions, and threat monitoring.",
    primaryHref: "/admin/audit-logs",
    badge: "Security & Auditing",
    iconName: "ShieldAlert",
    items: [
      { name: "Security Dashboard", href: "/admin/audit-logs" },
      { name: "Audit Logs", href: "/admin/audit-logs" },
      { name: "Login Logs", href: "/admin/audit-logs" },
      { name: "Security Events", href: "/admin/system-health" },
      { name: "Permission Management", href: "/admin/feature-flags" },
      { name: "Roles Management", href: "/admin/users" },
      { name: "Admin Roles", href: "/admin/users" },
      { name: "Access Control", href: "/admin/api-keys" },
      { name: "API Activity", href: "/admin/api-keys" },
      { name: "Suspicious Activity", href: "/admin/system-health" },
      { name: "Blocked Accounts", href: "/admin/users" },
    ],
  },

  // 46. Admin Settings
  {
    id: 46,
    category: "Super Admin Console",
    title: "46. Admin Settings",
    tagline: "Global environment configuration, feature toggles, maintenance mode, and system parameters.",
    primaryHref: "/admin/settings",
    badge: "Platform Config",
    iconName: "Settings",
    items: [
      { name: "Platform Settings", href: "/admin/settings" },
      { name: "General Settings", href: "/admin/settings" },
      { name: "Authentication Settings", href: "/admin/settings" },
      { name: "Email Settings", href: "/admin/settings" },
      { name: "SMS Settings", href: "/admin/settings" },
      { name: "Notification Settings", href: "/admin/settings" },
      { name: "Payment Settings", href: "/admin/settings" },
      { name: "Tax Settings", href: "/admin/settings" },
      { name: "Storage Settings", href: "/admin/settings" },
      { name: "Security Settings", href: "/admin/settings" },
      { name: "API Settings", href: "/admin/api-keys" },
      { name: "Feature Flags", href: "/admin/feature-flags" },
      { name: "Maintenance Mode", href: "/admin/maintenance" },
      { name: "System Configuration", href: "/admin/settings" },
    ],
  },

  // 47. Global Error / System Pages
  {
    id: 47,
    category: "Global Error & System",
    title: "47. Global Error / System Pages",
    tagline: "Every essential error, system state, connection failure, and session termination screen.",
    primaryHref: "/system/loading",
    badge: "15 System States",
    iconName: "AlertTriangle",
    items: [
      { name: "404 Not Found", href: "/system/404" },
      { name: "403 Forbidden", href: "/system/403" },
      { name: "401 Unauthorized", href: "/system/401" },
      { name: "500 Server Error", href: "/system/500" },
      { name: "Network Error", href: "/system/network-error" },
      { name: "Offline Page", href: "/system/offline" },
      { name: "Maintenance Page", href: "/maintenance" },
      { name: "Loading Page", href: "/system/loading" },
      { name: "Empty State", href: "/system/empty-state" },
      { name: "Access Denied", href: "/system/access-denied" },
      { name: "Session Expired", href: "/session-expired" },
      { name: "Verification Failed", href: "/verification-failed" },
      { name: "Upload Failed", href: "/system/upload-failed" },
      { name: "Payment Failed", href: "/system/payment-failed" },
      { name: "Something Went Wrong", href: "/system/something-went-wrong" },
    ],
  },
];
